trigger: none
  # batch: 'true'
  # branches:
  #   include: [ master ]
  # tags:
  #   exclude: [ NoBuild ]

stages:
# Subscription
- stage: Subscription
  variables:
    ENV: G0
    PREFIX : AZC1
  jobs:
  - job: Subscription_RBAC
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'ADF_AZC1-ADF-RG-G0'
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/AzDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "sub-InitialRG" -FullUpload' 
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
# # G1
# - stage: G1
#   variables:
#     ENV: G1
#     PREFIX : AZC1
#   jobs:
#   - job: RG_RBAC
#     pool:
#       vmImage: windows-2019
#     steps:
#     - task: AzurePowerShell@5
#       inputs:
#         azureSubscription: 'ADF_AZC1-ADF-RG-G0'
#         ScriptType: 'FilePath'
#         ScriptPath: 'ADF/release-az/AzDeploy.ps1'
#         ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "sub-InitialRG"'
#         FailOnStandardError: true
#         azurePowerShellVersion: 'LatestVersion'
# # P0
# - stage: P0
#   variables:
#     ENV: P0
#     PREFIX : AZC1
#   jobs:
#   - job: RG_RBAC
#     pool:
#       vmImage: 'windows-2019'
#     steps:
#     - task: AzurePowerShell@5
#       inputs:
#         azureSubscription: 'ADF_AZC1-ADF-RG-G0'
#         ScriptType: 'FilePath'
#         ScriptPath: 'ADF/release-az/AzDeploy.ps1'
#         ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "sub-InitialRG"'
#         FailOnStandardError: true
#         azurePowerShellVersion: 'LatestVersion'
# # S1
# - stage: S1
#   variables:
#     ENV: S1
#     PREFIX : AZC1
#   jobs:
#   - job: RG_RBAC
#     pool:
#       vmImage: windows-2019
#     steps:
#     - task: AzurePowerShell@5
#       inputs:
#         azureSubscription: 'ADF_AZC1-ADF-RG-G0'
#         ScriptType: 'FilePath'
#         ScriptPath: 'ADF/release-az/AzDeploy.ps1'
#         ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "sub-InitialRG"'
#         FailOnStandardError: true
#         azurePowerShellVersion: 'LatestVersion'

