trigger: none
  # batch: 'true'
  # branches:
  #   include: [ master ]
  # tags:
  #   exclude: [ NoBuild ]

stages:
# G1 - Sub Deploy (G0)
- stage: G1_Sub
  variables:
    ENV: G1
    PREFIX : AZC1
  jobs:
  - job: RG_RBAC
    pool:
      vmImage: windows-2019
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'ADF_AZC1-ADF-RG-G0'
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/AzDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "sub-InitialRG" -FullUpload'
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'

# G1 - RG Deploy
- stage: G1_RG
  variables:
    ENV: G1
    PREFIX : AZC1
  jobs:
  - job: Initial_G1
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'ADF_AZC1-ADF-RG-G1'
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/AzDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(Prefix)'
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
