trigger: none
  # batch: 'true'
  # branches:
  #   include: [ master ]
  # tags:
  #   exclude: [ NoBuild ]


stages:
# D2
- stage: D2_RG
  variables:
    APP : ADF
    ENV: D2
    PREFIX : AZC1
  jobs:
  - job: Initial_D2
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'ADF_AZC1-BRW-ADF-RG-D2'
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/AzDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(Prefix) -FullUpload'
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'